In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [2]:
def expected(table):
    columns = np.shape(table)[0]
    rows = np.shape(table)[1]
    
    row_totals = []
    for i in range(rows):
        row_totals.append(table[0,i]+table[1,i])
        
    column_totals = []
    for i in range(columns):
        column_totals.append(sum(table[i,:]))
        
    grand_total = sum(column_totals)
    
    expected_count_col_1 = []
    for i in range(rows):
        expected_count_col_1.append((row_totals[i]*column_totals[0])/grand_total)
    
    expected_count_col_2 = []
    for i in range(rows):
        expected_count_col_2.append((row_totals[i]*column_totals[1])/grand_total)
    
    x = np.row_stack((expected_count_col_1, expected_count_col_2))
    
    return x

In [3]:
t=np.array([[4,2,2],[7,3,2]])
print(t)
print(expected(t))
print(expected(expected(t)))  # applying the function twice should give same as once
assert np.allclose(expected(t),[[4.4,2,1.6],[6.6,3,2.4]])
assert np.allclose(expected(t),expected(expected(t)))

[[4 2 2]
 [7 3 2]]
[[4.4 2.  1.6]
 [6.6 3.  2.4]]
[[4.4 2.  1.6]
 [6.6 3.  2.4]]


In [4]:
def statistic(table):
    
    def expected(table):
        columns = np.shape(table)[0]
        rows = np.shape(table)[1]
        row_totals = []
        for i in range(rows):
            row_totals.append(table[0,i]+table[1,i])
        column_totals = []
        for i in range(columns):
            column_totals.append(sum(table[i,:]))
        grand_total = sum(column_totals)
        expected_count_col_1 = []
        for i in range(rows):
            expected_count_col_1.append((row_totals[i]*column_totals[0])/grand_total)
        expected_count_col_2 = []
        for i in range(rows):
            expected_count_col_2.append((row_totals[i]*column_totals[1])/grand_total)
        x = np.row_stack((expected_count_col_1, expected_count_col_2))
        return x
    
    expected = expected(table)
    observed = table
    s_squared = []
    for i in range(len(expected[0])):
        s_squared.append(((observed[0,i]-expected[0,i])**2)/expected[0,i])
        s_squared.append(((observed[1,i]-expected[1,i])**2)/expected[1,i])
    s_squared = sum(s_squared)
    
    return s_squared

In [5]:
# Informal testing
print(statistic(np.array([[12,8],[9,6]])))
print(statistic(np.array([[6,10,4],[3,9,7]])))

0.0
1.8463863006799308


In [6]:
def p_value(table):
    ex = expected(table)
    if np.any(ex<5)==True:
        print('Error')
        return None
    rows,cols=np.shape(table)
    df=(rows-1)*(cols-1)
    chi = stats.chi2(df)
    F=chi.cdf
    pvalue=1-F(statistic(table))
    return pvalue

In [7]:
tests = np.array([[231,245],[21,47],[116,136],[312,449]])

print(tests)
print(expected(tests))
print(statistic(tests))
print(p_value(tests))

reject_5 = True
reject_1 = True
reject_01 = False

[[231 245]
 [ 21  47]
 [116 136]
 [312 449]]
[[77.04046243 89.26910726]
 [11.00578035 12.75272961]]
680.3968467636215
0.0


In [8]:
assert (reject_5==True or reject_5==False)